### ISSUE TITLE
Execution timeout caused by seemingly innocuous redundant constraint

### ISSUE THREAD

**Issue by matthewdelaney** [fnogatz/CHR.js#19]
Given the rule: a(0) / b(0) <=> b(1). This works as expected when adding the constraints a(0), b(0) in that order (the b(0) is replaced by b(1)). If, however, I add a(3), a(0), b(0), I get the error message: "Execution timeout: The solver uses more time to terminate than normal. Do you want to trace the program?".

The same thing happens with the rather more contrived rule: a(0), b(0) <=> a(0), b(1).

As far as I can see, the initial addition of a(3) to the store shouldn't cause this problem. I've verified this with the CHR implementation provided with SWI Prolog.

**Comment by fnogatz** [comment]
Thank you for your bug report! I have fixed the wrong return values and added a test to ensure its correctness. The new version is available on npm as `v2.0.14`.

The CHR.js version deployed at http://chrjs.net/playground.html got also updated. Make sure to do a hard refresh to load the new JavaScript files.

**Comment by matthewdelaney** [comment]
Awesome! Thank you!
