### ISSUE TITLE
The fibonacci  example from the Readme doesn't behave as expected.

### ISSUE THREAD

**Issue by nextmood** [fnogatz/CHR.js#27]
Using node v6.10.3 and running the fibonacci script provided, **i got the following result:**

1   fib(1,1)  
2   fib(2,1)  
3   upto(5)   
4   fib(3,2)  
5   fib(3,2)  
6   fib(4,3)  
7   fib(4,3)  
8   fib(5,5)  
9   fib(5,5)  
10  fib(5,5)  
11  fib(5,5) 

**instead of:**
    1   fib(1,1)  
    2   fib(2,1)  
    3   upto(5)   
    4   fib(3,2)  
    5   fib(4,3)  
    6   fib(5,5)

**Comment by fnogatz** [comment]
Thank you for reporting this! It happens due to the missing `Promise.then` callback. I updated the `README.md` accordingly so you can now simply copy the JS snippet into a file `fib.js`, call it via `node fib.js`, and get the correct result.
