### ISSUE TITLE
null can no longer be used as a value

### ISSUE THREAD

**Issue by matthewdelaney** [fnogatz/CHR.js#28]
I have some rules of the form a(null) ==> b(null). These worked earlier in the year but now, if there is a null in a rule, it appears to get replaced by white-space which causes the compiler to fail.

**Comment by fnogatz** [comment]
Thank you for the bug report! I fixed this in v3.0.2. It works now with `null` values as in [here](http://chrjs.net/playground.html?gist=3b3011ea47ef1c9ac44fda2d038c8a06).
